printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: "none"
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
endOfLine: "lf"

# overrides:
#     - files:
#         - "*.html"
#         - "*.jsx"
#         - "*.js"
#       options:
#           tabWidth: 2
